version: "2"
services:
 market-php:
  build: .
  container_name: market-php-web-1
  user: root
  restart: always
  ports:
   - "8086:80"
  environment:
   - APP_NAME=Market
   - APP_ENV=local
   - APP_KEY=base64:2RE5uZ0jY6fdpW8vUspP72+GrPHtYMn1M5y2KAqGW7Y=
   - APP_DEBUG=false
   - APP_LOG_LEVEL=debug
   - APP_URL=http://172.31.10.18:8086/
   - APP_LANG=zh
   - DB_CONNECTION=mysql
   - DB_HOST=172.31.10.18
   - DB_PORT=3306
   - DB_DATABASE=market
   - DB_USERNAME=root
   - DB_PASSWORD=3Aab71iuXIA4FDdaNF1jLeJN1
   - BROADCAST_DRIVER=log
   - CACHE_DRIVER=file
   - SESSION_DRIVER=file
   - SESSION_LIFETIME=120
   - QUEUE_DRIVER=redis
   - REDIS_HOST=172.31.10.18
   - REDIS_PASSWORD=RVD4mjpYSdTEDSOl24Ti17OIy
   - REDIS_PORT=6379
   - MAIL_DRIVER=smtp
   - MAIL_HOST=smtp.mailtrap.io
   - MAIL_PORT=2525
   - MAIL_USERNAME=null
   - MAIL_PASSWORD=null
   - MAIL_ENCRYPTION=null
   - MAIL_FROM_ADDRESS=null
   - MAIL_FROM_NAME=null
   - PUSHER_APP_ID=
   - PUSHER_APP_KEY=
   - PUSHER_APP_SECRET=
   - PUSHER_APP_CLUSTER=
  volumes:
   - "/home/market-log/:/www/wwwroot/market/storage/logs/"
